spring:
  redis:
    host: 47.105.98.113
    password: 1227
    port: 6379
    lettuce:
      pool:
        max-idle: 8 #最大空闲数
        max-active: 8 #最大连接数,负值表示没有限制
        min-idle: 0 #最小空闲数
        max-wait: 1000 #连接池最大阻塞等待时间
      shutdown-timeout: 100 #关闭超时时间
